// The iteration loop — Layer 2 core.
//
// Teaching note: This file owns:
//   1. Loading the seed Epic from Layer 1 (artifacts/epics/{ideaId}/raw.json)
//   2. The iteration state (best score, feedback threading)
//   3. File persistence (artifacts/epics/{ideaId}/*.json)
//   4. The inject_artifact call at the end — this is the Layer 2 → target project handoff
//   5. Progress callbacks so main.ts can display output without coupling to the loop
//
// Key pedagogical moment: `previousHints` threads improvement hints forward across iterations.
// The seed Epic from define_epic gives the loop a structured starting point — not a blank slate.

import * as fs from "fs";
import * as path from "path";
import { generate } from "./generator.js";
import { evaluate } from "./evaluator.js";
import { loadRawEpic, injectArtifact } from "../mcp/artifacts/store.js";
import { settings } from "../shared/config.js";
import type { Epic, EvaluationResult, IterationLog, RunManifest } from "../shared/types/index.js";

// ─── Progress Callbacks ───────────────────────────────────────────────────────

export interface LoopCallbacks {
  onIterationStart: (i: number, total: number) => void;
  onGenerated: (epic: Epic) => void;
  onEvaluated: (result: EvaluationResult, isBest: boolean, bestScore: number) => void;
  onComplete: (best: Epic, bestResult: EvaluationResult, runDir: string, injectedPath: string) => void;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function epicsDir(ideaId: string): string {
  return path.join(settings.artifactsRoot, "epics", ideaId);
}

function writeJson(filePath: string, data: unknown): void {
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), "utf-8");
}

// Format best epic as readable markdown for injection into target project
function formatEpicAsMarkdown(epic: Epic, score: number, ideaId: string): string {
  const lines = [
    `# Epic: ${epic.title}`,
    ``,
    `> Autoresearch score: **${score}/10** | Idea: \`${ideaId}\``,
    ``,
    `## Outcome`,
    epic.outcome,
    ``,
    `## Scope`,
    ``,
    `**In scope:**`,
    ...epic.scope.in.map((s) => `- ${s}`),
    ``,
    `**Out of scope:**`,
    ...epic.scope.out.map((s) => `- ${s}`),
    ``,
    `## Success Metrics`,
    ``,
    `| Metric | Target | Measurement |`,
    `|--------|--------|-------------|`,
    ...epic.success_metrics.map((m) => `| ${m.metric} | ${m.target} | ${m.measurement} |`),
    ``,
    `## Dependencies`,
    ...epic.dependencies.map((d) => `- ${d}`),
    ``,
    `## Risks`,
    ...epic.risks.map((r) => `- ${r}`),
    ``,
    `---`,
    `*Generated by autoresearch-pm-demo | ${new Date().toISOString()}*`,
  ];
  return lines.join("\n");
}

// ─── optimize() — main loop ───────────────────────────────────────────────────

export async function optimize(
  ideaId: string,
  targetDir: string,
  n: number,
  callbacks: LoopCallbacks
): Promise<{ best: Epic; bestResult: EvaluationResult; log: IterationLog[]; runDir: string; injectedPath: string }> {
  const runDir = epicsDir(ideaId);
  fs.mkdirSync(runDir, { recursive: true });

  // Load seed from Layer 1 MCP output (or use mock if no file exists in mock mode)
  let seed = loadRawEpic(ideaId);
  if (!seed) {
    if (settings.mockMode) {
      // In mock mode with no seed file, use iteration 0 fixture as seed
      seed = await generate({} as Epic, null); // will return mock fixture[0]
    } else {
      throw new Error(
        `No raw epic found at artifacts/epics/${ideaId}/raw.json\n` +
        `Run define_epic MCP tool first, or use --mock for offline demo.`
      );
    }
  }

  const iterationLog: IterationLog[] = [];
  let current = seed;
  let best: Epic = seed;
  let bestResult: EvaluationResult | null = null;
  let bestScore = -1;
  let initialScore = 0;
  let previousHints: string[] | null = null;

  for (let i = 0; i < n; i++) {
    callbacks.onIterationStart(i + 1, n);

    // GENERATE — improve current epic using previous iteration's hints
    const epic = await generate(current, previousHints);
    callbacks.onGenerated(epic);

    // EVALUATE
    const result = await evaluate(epic, i);

    // SELECT
    const isBest = result.total > bestScore;
    if (isBest) {
      best = epic;
      bestResult = result;
      bestScore = result.total;
    }
    if (i === 0) initialScore = result.total;

    callbacks.onEvaluated(result, isBest, bestScore);

    // Persist this iteration
    const log: IterationLog = { iteration: i, epic, result, isBest };
    iterationLog.push(log);
    writeJson(path.join(runDir, `iteration_${i}.json`), log);

    // Thread hints forward — this is the optimization mechanism
    previousHints = result.improvementHints;
    current = epic;
  }

  // Persist final outputs
  writeJson(path.join(runDir, "best.json"), { epic: best, result: bestResult });

  // ── INJECT: push best epic as markdown into target project ─────────────────
  // This is the Layer 2 → build handoff. Same injectArtifact function
  // as used by the MCP layer's inject_artifact tool.
  const filename = `${ideaId}-epic.md`;
  const markdown = formatEpicAsMarkdown(best, bestScore, ideaId);
  const injectedPath = injectArtifact(targetDir, filename, markdown);

  const manifest: RunManifest = {
    runId: `${ideaId}-${Date.now().toString(36)}`,
    ideaId,
    task: best.title,
    iterations: n,
    finalScore: bestScore,
    initialScore,
    improvementDelta: bestScore - initialScore,
    injectedPath,
    timestamp: new Date().toISOString(),
    model: settings.mockMode ? "mock" : settings.model,
    mockMode: settings.mockMode,
  };
  writeJson(path.join(runDir, "manifest.json"), manifest);

  callbacks.onComplete(best, bestResult!, runDir, injectedPath);

  return { best, bestResult: bestResult!, log: iterationLog, runDir, injectedPath };
}
